apiVersion: v1
kind: Service
metadata:
  name: earbug
  annotations:
    tailscale.com/hostname: earbug-ihwa
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
      appProtocol: HTTP
  selector:
    app.kubernetes.io/name: earbug
