apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

buildMetadata:
  - managedByLabel
  - originAnnotations

patches:
  - patch: |
      apiVersion: v1
      kind: Service
      metadata:
        name: earbug
        annotations:
          tailscale.com/hostname: earbug-ihwa
      spec:
        type: LoadBalancer
        loadBalancerClass: tailscale
  - patch: |
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: earbug
      spec:
        template:
          spec:
            containers:
              - name: earbug
                env:
                  - name: OTEL_SERVICE_NAME
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.labels['app.kubernetes.io/name']
                  - name: POD_UID
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.uid
                  - name: OTEL_RESOURCE_ATTRIBUTES
                    value: k8s.pod.uid=$(POD_UID),k8s.cluster.name=ihwa,k8s.container.name=earbug
                  - name: OTEL_EXPORTER_OTLP_ENDPOINT
                    value: http://ingest.otelcol.svc:4317
                  - name: GOOGLE_APPLICATION_CREDENTIALS
                    value: /var/run/secrets/google/key.json
                volumeMounts:
                  - mountPath: /var/run/secrets/google
                    name: gcp
            volumes:
              - name: gcp
                secret:
                  secretName: gcp

generators:
  - |
    apiVersion: viaduct.ai/v1
    kind: ksops
    metadata:
      name: earbug
      annotations:
        config.kubernetes.io/function: |
          exec:
            path: /opt/kustomize/ksops
    files:
      - secrets.enc.k8s.yaml

resources:
  - ../base
  - httproute.k8s.yaml
  - namespace.k8s.yaml
