apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

buildMetadata:
  - managedByLabel
  - originAnnotations

patches:
  - patch: |
      apiVersion: v1
      kind: Service
      metadata:
        name: earbug
        annotations:
          tailscale.com/hostname: earbug-ihwa
      spec:
        type: LoadBalancer
        loadBalancerClass: tailscale
  - patch: |
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: earbug
      spec:
        template:
          spec:
            containers:
              - name: earbug
                env:
                  - name: GOOGLE_APPLICATION_CREDENTIALS
                    value: /var/run/secrets/google/key.json
                volumeMounts:
                  - mountPath: /var/run/secrets/google
                    name: gcp
            volumes:
              - name: gcp
                secret:
                  secretName: gcp

generators:
  - |
    apiVersion: viaduct.ai/v1
    kind: ksops
    metadata:
      name: ghdefaults
      annotations:
        config.kubernetes.io/function: |
          exec:
            path: /opt/kustomize/ksops
    files:
      - secrets.enc.k8s.yaml

resources:
  - ../base
  - httproute.k8s.yaml
  - namespace.k8s.yaml
