steps:
  - name: "us-central1-docker.pkg.dev/com-seankhliao/build/gotip:latest"
    entrypoint: sh
    env:
      - CGO_ENABLED=0
    args:
      - -c
      - |
        go test -vet=all ./... && \
        go build ./...
