apiVersion: skaffold/v3
kind: Config
metadata:
  name: earbug
build:
  artifacts:
    - image: us-central1-docker.pkg.dev/com-seankhliao/run/earbug
      ko:
        env:
          - CGO_ENABLED=0
        flags:
          - -trimpath
        ldflags:
          - -s
          - -w
        dependencies:
          paths:
            - "**/*.go"
            - "server/**/*"
            - "kodata/**/*"
            - "go.mod"

  tagPolicy:
    inputDigest: {}
      
  platforms:
    - linux/amd64

  local:
    concurrency: 0

manifests:
  rawYaml:
    - deploy/cloudrun/service.yaml
  
deploy:
  cloudrun:
    region: us-central1
