apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: earbug
build:
  artifacts:
    - image: ghcr.io/seankhliao/earbug
      ko:
        fromImage: cgr.dev/chainguard/static@sha256:67a1b00e0134e2b3a614c7198a26f7deed9d11b7acad4d52c79c0cfd47a2eae7
        env:
          - CGO_ENABLED=0
        flags:
          - -trimpath
        ldflags:
          - -s
          - -w
        dependencies:
          paths:
            - "go.mod"
            - "**/*.go"
  tagPolicy:
    inputDigest: {}
  platforms:
    - linux/amd64
    - linux/arm64
deploy:
  kubeContext: ihwa
  kubectl:
    defaultNamespace: earbug
manifests:
  kustomize:
    buildArgs:
      - --enable-alpha-plugins
      - --enable-exec
    paths:
      - deploy/k8s/ihwa
profiles:
  - name: ihwa
  - name: local
    deploy:
      kubeContext: kind-kind
    manifests:
      kustomize:
        paths:
          - deploy/k8s/kind
    patches:
      - path: /build/artifacts/0/image
        value: ko.local/seankhliao/earbug
