apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
  labels:
    cloud.googleapis.com/location: us-central1
  name: earbug-liao-dev
  namespace: '330311169810'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: LOG_VERBOSITY
          value: '1'
        - name: LOG_FORMAT
          value: json+gcp
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: aeolian.liao.dev:4317
        - name: OTLP_AUDIENCE
          value: https://aeolian.liao.dev
        - name: EARBUG_BUCKET
          value: earbug-liao-dev
        - name: EARBUG_SPOTIFY_ID
          valueFrom:
            secretKeyRef:
              key: latest
              name: earbug-client-id
        - name: EARBUG_SPOTIFY_SECRET
          valueFrom:
            secretKeyRef:
              key: latest
              name: earbug-client-secret
        - name: LOG_ERRORS_GCHAT
          valueFrom:
            secretKeyRef:
              key: latest
              name: earbug-errors-gchat
        image: us-central1-docker.pkg.dev/com-seankhliao/run/earbug
        ports:
        - containerPort: 8080
          name: h2c
        resources:
          limits:
            cpu: 1000m
            memory: 128Mi
      serviceAccountName: earbug-liao-dev@com-seankhliao.iam.gserviceaccount.com
      timeoutSeconds: 5
  traffic:
  - latestRevision: true
    percent: 100
